In [2]:
import csv
import numpy as np

# Abra o arquivo CSV para leitura
with open('data.csv', 'r') as csvfile:
    # Crie um leitor CSV
    csvreader = csv.reader(csvfile)

    # Initialize lists to store values
    q1_values = []
    q2_values = []

    # Initialize variables for max and min values
    max_q1 = float('-inf')
    min_q1 = float('inf')

    max_q2 = float('-inf')
    min_q2 = float('inf')

    # Itere pelas linhas do arquivo CSV
    for row in csvreader:
        if len(row) == 2:
            q1_parts = row[0].split('=')  # Divide a primeira coluna em partes
            q2_parts = row[1].split('=')  # Divide a segunda coluna em partes

            if len(q1_parts) == 2:
                q1_value = float(q1_parts[1])
                q1_values.append(q1_value)
                max_q1 = max(max_q1, q1_value)
                min_q1 = min(min_q1, q1_value)

            if len(q2_parts) == 2:
                q2_value = float(q2_parts[1])
                q2_values.append(q2_value)
                max_q2 = max(max_q2, q2_value)
                min_q2 = min(min_q2, q2_value)

    # Convert lists to NumPy arrays
    q1_values = np.array(q1_values)
    q2_values = np.array(q2_values)

    # Calculate mean, std, max, and min
    mean_q1 = np.mean(q1_values)
    std_q1 = np.std(q1_values)

    mean_q2 = np.mean(q2_values)
    std_q2 = np.std(q2_values)

    print(f"Q1: Mean={mean_q1:.2f}, Std={std_q1:.2f}, Max={max_q1:.2f}, Min={min_q1:.2f}")
    print(f"Q2: Mean={mean_q2:.2f}, Std={std_q2:.2f}, Max={max_q2:.2f}, Min={min_q2:.2f}")

Q1: Mean=64.82, Std=64.79, Max=187.15, Min=-56.06
Q2: Mean=153.42, Std=65.55, Max=299.99, Min=36.81

## Summary

q1: -56.06 ~ 187.15

q2: 36.81 ~ 299.99

## Empirical Data


q1=187.15, q2=287.76

q1=99.35, q2=179.95

q1=51.28, q2=133.60

q1=30.28, q2=105.66

q1=57.20, q2=143.32

q1=65.18, q2=135.28

q1=69.08, q2=147.09

q1=179.89, q2=266.67

q1=-39.86, q2=57.23

q1=110.54, q2=191.77

q1=87.45, q2=175.78

q1=68.17, q2=140.21

q1=107.33, q2=188.33

q1=-6.13, q2=92.16

q1=170.05, q2=248.26

q1=-23.04, q2=71.22

q1=61.25, q2=139.35

q1=17.48, q2=95.80

q1=-56.06, q2=36.81

q1=119.42, q2=190.73

q1=22.86, q2=130.18

q1=184.52, q2=299.99

q1=7.26, q2=114.00

q1=-10.33, q2=72.68

q1=31.92, q2=113.15

q1=28.35, q2=107.81

q1=119.97, q2=232.33

q1=98.32, q2=180.94

q1=150.20, q2=255.90

q1=-22.47, q2=71.79

q1=8.50, q2=95.46

q1=-8.53, q2=103.82

q1=160.60, q2=244.72

q1=45.22, q2=115.91

q1=123.68, q2=210.25

q1=130.52, q2=239.87

q1=46.23, q2=138.59

q1=16.34, q2=94.67

q1=-41.40, q2=75.93

q1=69.90, q2=161.92

q1=102.34, q2=208.29

q1=103.32, q2=184.11

q1=136.83, q2=217.97

q1=148.38, q2=232.99

q1=38.37, q2=115.32

q1=96.29, q2=174.72

q1=-39.60, q2=41.21

q1=30.32, q2=105.70

q1=42.21, q2=150.48